notifications:
  email:
    recipients:
      - red-data-tools@ml.commit-email.info

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9

before_script:
  - ruby -rpp -rrbconfig -e 'pp RbConfig::CONFIG'
