notifications:
  email:
    recipients:
      - red-data-tools@ml.commit-email.info

dist: xenial

matrix:
  include:
    - name: "2.3"
      rvm: 2.3
    - name: "2.4"
      rvm: 2.4
    - name: "2.5"
      rvm: 2.5
    - name: "2.6"
      rvm: 2.6
    - name: "trunk"
      rvm: ruby-head
    - name: "macOS + Xcode 9.2"
      os: osx
      osx_image: xcode9.2
    - name: "macOS + Xcode 9.3"
      os: osx
      osx_image: xcode9.3
    - name: "macOS + Xcode 9.4"
      os: osx
      osx_image: xcode9.4
    - name: "macOS + Xcode 10.0"
      os: osx
      osx_image: xcode10
    - name: "macOS + Xcode 10.1"
      os: osx
      osx_image: xcode10.1
    - name: "macOS + Xcode 10.2"
      os: osx
      osx_image: xcode10.2
    - name: "macOS + Xcode 10.3"
      os: osx
      osx_image: xcode10.3
    - name: "macOS + Xcode 11"
      os: osx
      osx_image: xcode11
