version: "{build}"
clone_depth: 10

notifications:
  - provider: Webhook
    url: https://webhook.commit-email.info/

environment:
  matrix:
    - ruby_version: "24"
    - ruby_version: "24-x64"
    - ruby_version: "25"
    - ruby_version: "25-x64"
    - ruby_version: "26"
    - ruby_version: "26-x64"

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ridk exec pacman -Syu --noconfirm
  - bundle install

build_script:
  - bundle exec ruby -rdevkit -S rake configure:debug
  - ridk exec make -C ext\extpp

test_script:
  - bundle exec ruby -rdevkit -S rake test
