version: "{build}"
clone_depth: 10

notifications:
  - provider: Webhook
    url: https://webhook.commit-email.info/

environment:
  matrix:
    - ruby_version: "24"
    - ruby_version: "24-x64"
    - ruby_version: "25"
    - ruby_version: "25-x64"
    - ruby_version: "26"
    - ruby_version: "26-x64"
    - ruby_version: "27"
    - ruby_version: "27-x64"

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ps: |
      Invoke-WebRequest `
        -Uri https://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz `
        -OutFile msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
  - |
    ridk exec pacman `
      --noconfirm `
      --upgrade `
      msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz
  - ridk exec pacman --sync --refresh --sysupgrade --noconfirm
  - taskkill /F /FI "MODULES eq msys-2.0.dll"
  - bundle install

build_script:
  - bundle exec ruby -rdevkit -S rake configure:debug
  - ridk exec make -C ext\extpp

test_script:
  - bundle exec ruby -rdevkit -S rake test
